### PR TITLE
Ivander fix trip duration

### LINKED ISSUE #108: [PE-D] Duration of a Trip
It is not clearly specified in the user guide on how to add the duration for a trip in the user guide. So every time I add a new trip the number of days of the trip just appears as 0 days. 

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: shreytheshreyas/ped#2

### PR DESCRIPTION
**Pull request by ivanderjmw**
Fix #108 
Add `getMaxDay()` tests.

### CODE REVIEW

File: src/main/java/seedu/trippie/data/TrippieData.java [hunk 1]
```diff
@@ -29,11 +29,20 @@ public String list() {
...
-            boolean plural = trip.getMaxDay() != 1;
-            String dayWord = plural ? "Days" : "Day";
-            list = list.concat(
-                    (trip.getIndex() + 1) + ". " + trip.getMaxDay() + " " + dayWord + " - " + trip.getName() + "\n"
-            );
+            int maxDay = trip.getMaxDay();
+
+            if (maxDay == 0) {
+                list = list.concat(
+                        (trip.getIndex() + 1) + ". " + trip.getName() + " " + "[No places or expenses added yet]" + "\n"
```
Comment (felixhalim) [inline src/main/java/seedu/trippie/data/TrippieData.java:36]: Great message

**Review by ShawnTanzc — APPROVED** [review]
Thanks for fixing the 0 days issue, LGTM

File: src/main/java/seedu/trippie/data/TrippieData.java [hunk 2]
```diff
@@ -29,11 +29,20 @@ public String list() {
...
+                );
+            } else {
+                boolean plural = maxDay != 1;
+                String dayWord = plural ? "Days" : "Day";
+
+                list = list.concat(
+                        (trip.getIndex() + 1) + ". " + trip.getName() + " [" + trip.getMaxDay() + " " + dayWord + "]\n"
```
Comment (felixhalim) [inline src/main/java/seedu/trippie/data/TrippieData.java:43]: This will affect the old test case

File: src/test/java/seedu/trippie/StorageTest.java [hunk 3]
```diff
@@ -55,13 +55,13 @@ public void loadMasterFile_sampleMasterFile_success() throws TrippieException {
...
         storage.loadMasterFile(sc, data);
 
-        String expectedTripListString = "1. 1 Day - Chigago run\n"
-                + "2. 2 Days - Jakarta Fest\n"
-                + "3. 3 Days - Malaysia\n"
-                + "4. 4 Days - Malaysia\n"
-                + "5. 5 Days - Australia\n"
-                + "6. 6 Days - America\n"
-                + "7. 7 Days - Africa\n";
+        String expectedTripListString = "1. Chigago run [1 Day]\n"
```
Comment (felixhalim) [inline src/test/java/seedu/trippie/StorageTest.java:58]: Nice! You updated the test-case

**Review by felixhalim — APPROVED** [review]
Good job, Ivander!

**Comment by ShawnTanzc** [comment]
Fix #108 as well
